NGC: &NGC
  docker_image: nvidian/prj-recsys/transf4rec_exp:0.1.0
  download_dir: /tmp
  hostname: ngc
  job_name: tranf4rec-job-autobench
  results_mount: /results

NGC_32GB_2GPU: &NGC_32GB_2GPU
  <<: *NGC
  instance: dgx1v.32g.2.norm

jobs:
  - steps:
      - nvidia-smi
      - wandb login 76eea90114bb1cdcbafe151b262e4a5d4ff60f12
      - date
      - git pull origin experimentation
      - date
      - bash script/get_dataset.bash
      - date
      - bash script/run_transformer_v2.bash test_experiments full session_cooccurrence --start_date 2019-10-01 --end_date 2019-10-05 --per_device_train_batch_size 256 --per_device_eval_batch_size 128 --model_type gpt2 --loss_type cross_entropy_neg --margin_loss 0.0 --d_model 64 --n_layer 4 --n_head 2 --hidden_act gelu --dropout 0.2 --learning_rate 1e-03  --similarity_type concat_mlp --num_train_epochs 15 --all_rescale_factor 1.0 --neg_rescale_factor 0.0 --inp_merge mlp --tf_out_activation tanh
      - date
    backend: *NGC_32GB_2GPU

  - steps:
      - nvidia-smi
      - wandb login 76eea90114bb1cdcbafe151b262e4a5d4ff60f12
      - date
      - git pull origin experimentation
      - date
      - bash script/get_dataset.bash
      - date
      - bash script/run_transformer_v2.bash test_experiments full session_cooccurrence --start_date 2019-10-01 --end_date 2019-10-05 --per_device_train_batch_size 256 --per_device_eval_batch_size 128 --model_type gpt2 --loss_type cross_entropy_neg --margin_loss 0.0 --d_model 64 --n_layer 2 --n_head 2 --hidden_act gelu --dropout 0.2 --learning_rate 1e-03  --similarity_type concat_mlp --num_train_epochs 15 --all_rescale_factor 1.0 --neg_rescale_factor 0.0 --inp_merge mlp --tf_out_activation tanh
      - date
    backend: *NGC_32GB_2GPU

reports:
  filename: exp_results
  types:
    - xls
    - pickle
