NGC: &NGC
  docker_image: nvidian/prj-recsys/transf4rec_exp:0.1.0
  download_dir: /tmp
  hostname: ngc
  job_name: tranf4rec-htune-v06-gpt2
  results_mount: /results

  datasets:
    /data: 66609

NGC_32GB_2GPU: &NGC_32GB_2GPU
  <<: *NGC
  instance: dgx1v.32g.2.norm

jobs:
  - steps:
      - nvidia-smi
      - wandb login 76eea90114bb1cdcbafe151b262e4a5d4ff60f12
      - date
      - git pull origin experimentation
      - date
      - bash script/run_transformer_v2.bash !{htune_study_name} full_noneg session_cooccurrence --start_date 2019-10-01 --end_date 2019-10-15 --model_type gpt2 --loss_type cross_entropy --per_device_eval_batch_size 128 --similarity_type concat_mlp --tf_out_activation tanh --all_rescale_factor 1.0 --neg_rescale_factor 0.0 --inp_merge mlp --hidden_act gelu_new --learning_rate_warmup_steps 0 --learning_rate_num_cosine_cycles 4.0 --dataloader_drop_last --compute_metrics_each_n_steps 50 --max_seq_len 20 {training_hparams}
      - date
    backend: *NGC_32GB_2GPU


hyperparameters_tuning:
  goal: maximize
  metric: Test_ndcg@1000_all
  groups:
      - name: training_hparams
        hparams:
          - name: --num_train_epochs
            sampling: int_uniform
            min_value: 1
            max_value: 10

          - name: --per_device_train_batch_size
            sampling: int_uniform
            min_value: 64
            max_value: 256
            step_value: 64

          - name: --learning_rate
            sampling: log_uniform
            min_value: 0.0001
            max_value: 0.01

          - name: --learning_rate_schedule
            sampling: categorical
            categ_values:
              - constant_with_warmup
              - linear_with_warmup
              - cosine_with_warmup

          - name: --dropout
            sampling: discrete_uniform
            min_value: 0.0
            max_value: 0.3
            step_value: 0.1 

          - name: --weight_decay
            sampling: log_uniform
            min_value: 0.000001
            max_value: 0.0001

          - name: --d_model
            sampling: int_uniform
            min_value: 64
            max_value: 320
            step_value: 64

          - name: --n_layer
            sampling: int_uniform
            min_value: 1
            max_value: 4

          - name: --n_head
            sampling: categorical
            categ_values:
              - 1
              - 2
              - 4
              - 8
              - 16


reports:
  filename: exp_results
  types:
    - xls
    - pickle
