sess_pid_seq:
    dtype: categorical
    cardinality: 390000
    is_label: True
    emb_table: product_id
    log_with_preds_as_metadata: True
sess_ccid_seq:
    dtype: categorical
    cardinality: 150
    emb_table: category_id
    log_with_preds_as_metadata: True
sess_csid_seq:
    dtype: categorical
    cardinality: 800
    emb_table: category_s_id
    log_with_preds_as_metadata: True
sess_bid_seq:
    dtype: categorical
    cardinality: 5000
    emb_table: brand
    log_with_preds_as_metadata: True
sess_price_seq:
    dtype: float    
sess_relative_price_to_avg_category_seq:
    dtype: float
sess_product_recency_seq:
    dtype: float
    log_with_preds_as_metadata: True

user_pid_seq_bef_sess:
    dtype: categorical
    cardinality: 390000
    is_label: False
    emb_table: product_id
    log_with_preds_as_metadata: False
user_ccid_seq_bef_sess:
    dtype: categorical
    cardinality: 150
    emb_table: category_id
    log_with_preds_as_metadata: False
user_csid_seq_bef_sess:
    dtype: categorical
    cardinality: 800
    emb_table: category_s_id
    log_with_preds_as_metadata: False
user_bid_seq_bef_sess:
    dtype: categorical
    cardinality: 5000
    emb_table: brand
    log_with_preds_as_metadata: False
user_price_seq_bef_sess:
    dtype: float    
user_relative_price_to_avg_category_seq_bef_sess:
    dtype: float
user_product_recency_seq_bef_sess:
    dtype: float
    log_with_preds_as_metadata: False