sess_pid_seq:
    dtype: categorical
    cardinality: 300000
    is_label: True
    emb_table: product_id
sess_ccid_seq:
    dtype: categorical
    cardinality: 700
    emb_table: category_id
sess_price_seq:
    dtype: float
sess_csid_seq:
    dtype: categorical
    cardinality: 700
    emb_table: category_s_id
sess_bid_seq:
    dtype: categorical
    cardinality: 10000
    emb_table: brand
sess_relative_price_to_avg_category_seq:
    dtype: float
sess_product_recency_seq:
    dtype: float
sess_neg_pids:
    dtype: categorical
    cardinality: 300000
    emb_table: product_id
sess_neg_sess_ccid_seq:
    dtype: categorical
    cardinality: 700
    emb_table: category_id
sess_neg_sess_price_seq:
    dtype: float
sess_neg_sess_csid_seq:
    dtype: categorical
    cardinality: 700
    emb_table: category_s_id
sess_neg_sess_bid_seq:
    dtype: categorical
    cardinality: 10000
    emb_table: brand
sess_neg_sess_relative_price_to_avg_category_seq:
    dtype: float
sess_neg_sess_product_recency_seq:
    dtype: float
