sess_pid_seq:
    dtype: categorical
    cardinality: 390000
    is_label: True
    emb_table: product_id
    log_with_preds_as_metadata: True
sess_ccid_seq:
    dtype: categorical
    cardinality: 1000
    emb_table: category_id
    log_with_preds_as_metadata: True
sess_relative_price_to_avg_category_seq:
    dtype: float