sess_pid_seq:
    dtype: categorical
    cardinality: 390000
    is_label: True
    emb_table: product_id
    log_with_preds_as_metadata: True

user_pid_seq_bef_sess:
    dtype: categorical
    cardinality: 390000
    is_label: False
    emb_table: product_id
    log_with_preds_as_metadata: False    