NGC: &NGC
  docker_image: nvidian/prj-recsys/transf4rec_exp:0.1.0
  download_dir: /tmp
  hostname: ngc
  job_name: tranf4rec-job-autobench
  results_mount: /results

  datasets:
    /data: 66173

NGC_32GB_2GPU: &NGC_32GB_2GPU
  <<: *NGC
  instance: dgx1v.32g.2.norm

jobs:
  - steps:
      - nvidia-smi
      - wandb login 76eea90114bb1cdcbafe151b262e4a5d4ff60f12
      - date
      - git pull origin experimentation
      - date
      - bash script/run_transformer_v2.bash !{htune_study_name} full session_cooccurrence --start_date 2019-10-01 --end_date 2019-10-15 --model_type gru --num_train_epochs 15 --loss_type cross_entropy --per_device_eval_batch_size 128 --similarity_type concat_mlp --tf_out_activation tanh --all_rescale_factor 1.0 --neg_rescale_factor 0.0 --inp_merge mlp {training_hparams}
      - date
    backend: *NGC_32GB_2GPU


hyperparameters_tuning:
  goal: maximize
  metric: Test_ndcg@1000_all
  groups:
      - name: training_hparams
        hparams:
          - name: --per_device_train_batch_size
            sampling: categorical
            categ_values:
              - 64
              - 128
              - 256

          - name: --learning_rate
            sampling: log_uniform
            min_value: 0.0005
            max_value: 0.1

          - name: --dropout
            sampling: discrete_uniform
            min_value: 0.0
            max_value: 0.3
            step_value: 0.1     

          - name: --d_model
            sampling: categorical
            categ_values:
              - 32
              - 64
              - 128       

          - name: --n_layer
            sampling: int_uniform
            min_value: 1
            max_value: 4


reports:
  filename: exp_results
  types:
    - xls
    - pickle
